
networks:
    symfony:
        driver: bridge
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        user: "1000:1000"
        ports:
            - "8080:8080"
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        container_name: symfony-app
        networks:
            - symfony
    nginx:
        container_name: nginx
        image: "nginx:stable-alpine"
        restart: always
        ports:
            - "8000:80"
        networks:
            - symfony
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
